roles/daily-borgbackup: error handling in shell script
... is horrible, like everything else.
https://stackoverflow.com/a/48081476/799204

diff --git a/roles/daily-borgbackup/files/cron.daily/local-borgbackup b/roles/daily-borgbackup/files/cron.daily/local-borgbackup
--- a/roles/daily-borgbackup/files/cron.daily/local-borgbackup
+++ b/roles/daily-borgbackup/files/cron.daily/local-borgbackup
@@ -7,60 +7,68 @@ BORG_REPOS_DIR=/data/backup/borg
 # Otherwise, only show errors.
 BORG_PROGRESS=
 BORG_STATS=
+
 if tty>/dev/null; then
-        BORG_PROGRESS="--progress"
-        BORG_STATS="--stats --info"
+	BORG_PROGRESS="--progress"
+	BORG_STATS="--stats --info"
 fi
 
-# Write a log to show the time taken
+
+### Write a log to show the time taken ###
 log() {
-        echo >> /var/log/local-borgbackup -- "$@"
+	echo >> /var/log/local-borgbackup -- "$@"
 }
 log_date() {
-        log "$(date --rfc-3339=seconds)"
+	log "$(date --rfc-3339=seconds)"
+}
+
+# Log the start timestamp
+log_start() {
+	log_date
 }
 log_cmd() {
-        "$@"
-        log "$*"
-        log_date  # log time of completion
+	"$@"; RET=$?
+
+	log "$*" &&
+	log_date &&  # log time of completion
+	return $RET
 }
-# Log the start timestamp
-log_date
+
 
 # If the borg repo does not exist, create it - atomically.
 # If interrupted, just leaves a small randomly-named directory lying around
 borg_init() {
 	if [ ! -e "$1" ]; then
-		T=$(mktemp --dry-run "$1".tmp.XXXXXX)
-		borg init --encryption=none "$T"
+		T=$(mktemp --dry-run "$1".tmp.XXXXXX) &&
+		borg init --encryption=none "$T" &&
 
 		# ~5M segment size (borg 1.0 default) is too small IMO.
 		# Use ~500M (borg 1.1 default).
-		sed -i "$T"/config -e 's/^max_segment_size = .*$/max_segment_size = 524288000/'
+		sed -i "$T"/config -e 's/^max_segment_size = .*$/max_segment_size = 524288000/' &&
 
 		mv "$T" "$1"
-	fi
+	fi &&
 
-	# borg doesn't like renames.
+	# borg doesn't like renamed repos.  Coddle it.
 	# There's an easier fix in 1.1, which might even work before the rename
 	# (so we don't end up overriding borg *after* the initial creation).
 	# It would also avoid a warning which we have to suppress.
 	# https://github.com/borgbackup/borg/issues/1910#issuecomment-354780246
 	(
-		export BORG_REPO="$1"
-		export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes
-		borg delete ::temp 2>/dev/null
-		borg create ::temp - </dev/null 2>/dev/null
+		export BORG_REPO="$1" &&
+		export BORG_RELOCATED_REPO_ACCESS_IS_OK=yes &&
+		borg delete ::temp 2>/dev/null &&
+		borg create ::temp /dev/null &&
 		borg delete ::temp
 	)
 }
 
 backup_home() {
-	HOME_DIR=/home/"$1"
-	BORG_REPO="$BORG_REPOS_DIR"/"$1"
-	export BORG_REPO
+	HOME_DIR=/home/"$1" &&
+	BORG_REPO="$BORG_REPOS_DIR"/"$1" &&
+	export BORG_REPO &&
 
-	borg_init "$BORG_REPO"
+	borg_init "$BORG_REPO" &&
 
 	# Exclusions:
 	#
@@ -83,7 +91,7 @@ backup_home() {
 		--exclude "$HOME_DIR"/.thunderbird/*/global-messages-db.sqlite \
 		--exclude "$HOME_DIR"/.icedove/*/global-messages-db.sqlite \
 		--exclude "$HOME_DIR"/.local/share/zeitgeist/fts.index \
-		--exclude "$HOME_DIR"/.local/share/tracker
+		--exclude "$HOME_DIR"/.local/share/tracker &&
 
 	# Prune old backups to save space
 	log_cmd borg prune $BORG_STATS \
@@ -96,28 +104,37 @@ backup_home() {
 # and I have a lot of bookmarks I want to keep.
 backup_firefox_bookmarks()
 {
-	HOME_DIR=/home/"$1"
+	HOME_DIR=/home/"$1" &&
 	if [ ! -d "$HOME_DIR"/.mozilla ]; then
 		return
-	fi
+	fi &&
 
-	BORG_REPO="$BORG_REPOS_DIR"/"$1".firefox-bookmarks
-	export BORG_REPO
+	BORG_REPO="$BORG_REPOS_DIR"/"$1".firefox-bookmarks &&
+	export BORG_REPO &&
 
-	borg_init "$BORG_REPO"
+	borg_init "$BORG_REPO" &&
 
-	log_cmd borg create $BORG_PROGRESS $BORG_STATS '::{now}' "$HOME_DIR"/.mozilla/firefox/*/bookmarkbackups
+	log_cmd borg create $BORG_PROGRESS $BORG_STATS '::{now}' \
+		"$HOME_DIR"/.mozilla/firefox/*/bookmarkbackups &&
 
 	log_cmd borg prune $BORG_STATS \
 		--keep-daily 14 --keep-weekly 4 \
 		--keep-monthly 12 --keep-yearly -1
 }
 
+# Note if any one backup step fails, we keep going.
+# However an error should be printed, which works well for a cron job.
 backup() {
 	backup_home "$1"
 	backup_firefox_bookmarks "$1"
 }
 
-backup mike
-backup sheena
-backup jenkins-photos
+main() {
+	log_start || exit 1
+
+	backup mike
+	backup sheena
+	backup jenkins-photos
+}
+
+main
