roles/daily-borgbackup: add final warning if an error was detected

diff --git a/roles/daily-borgbackup/files/cron.daily/local-borgbackup b/roles/daily-borgbackup/files/cron.daily/local-borgbackup
--- a/roles/daily-borgbackup/files/cron.daily/local-borgbackup
+++ b/roles/daily-borgbackup/files/cron.daily/local-borgbackup
@@ -1,5 +1,7 @@
 #!/bin/sh
-# Tested on Stretch i.e. borgbackup-1.0.9
+# Tested on Debian 9 "stretch", i.e. borgbackup-1.0.9
+
+set -o nounset
 
 BORG_REPOS_DIR=/data/backup/borg
 
@@ -27,11 +29,13 @@ log_start() {
 	log_date
 }
 log_cmd() {
-	"$@"; RET=$?
+    local rc=0
+
+	"$@" || rc=$?
 
 	log "$*" &&
 	log_date &&  # log time of completion
-	return $RET
+	return $rc
 }
 
 
@@ -109,7 +113,7 @@ backup_home() {
 
 	# Prune old backups to save space
 	log_cmd borg prune $BORG_STATS \
-		--keep-daily 14 --keep-weekly 4 \
+		--keep-daily 21 --keep-weekly 6 \
 		--keep-monthly 12 --keep-yearly -1
 }
 
@@ -132,23 +136,37 @@ backup_firefox_bookmarks()
 		"$HOME_DIR"/.mozilla/firefox/*/bookmarkbackups &&
 
 	log_cmd borg prune $BORG_STATS \
-		--keep-daily 14 --keep-weekly 4 \
+		--keep-daily 21 --keep-weekly 6 \
 		--keep-monthly 12 --keep-yearly -1
 }
 
 # Note if any one backup step fails, we keep going.
-# However an error should be printed, which works well for a cron job.
+# However an error should be printed, which works well for the cron job case.
+# Also make sure to point out if there was an error (like rsync does :).
 backup() {
-	backup_home "$1"
-	backup_firefox_bookmarks "$1"
+	local rc=0
+
+	backup_home "$1" ||
+		rc=1
+	backup_firefox_bookmarks "$1" ||
+		rc=1
+
+	return $rc
 }
 
 main() {
+	local rc=0
+
 	log_start || exit 1
 
-	backup mike
-	backup sheena
-	backup jenkins-photos
-}
+	for i in mike sheena jenkins-photos; do
+		backup "$i" || rc=1
+	done
 
+	if [ $rc != 0 ]; then
+		echo
+		echo "WARNING: an error occurred.  Some files may not be backed up."
+	fi
+	return $rc
+}
 main
